In [2]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd

# Load Excel file
file_path = "attendance_2026-01-01_to_2026-01-30.xlsx"
df = pd.read_excel(file_path)

In [3]:
df.head()

,ATTENDANCE SHEET PPMC,Unnamed: 1,Unnamed: 2,Unnamed: 3,Attendance Period: 2026-01-01 to 2026-01-30,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr,Employee ID,Employee Name,Department,2026-01-01,NaN,NaN,2026-01-02,NaN,NaN,...,2026-01-28,NaN,NaN,2026-01-29,NaN,NaN,2026-01-30,NaN,NaN,TOTAL HRS
2,NaN,NaN,NaN,NaN,IN,OUT,HRS,IN,OUT,HRS,...,IN,OUT,HRS,IN,OUT,HRS,IN,OUT,HRS,NaN
3,1,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,Absent,-,-,8:30 AM,4:33 PM,8:03,...,8:44 AM,5:51 PM,9:07,8:38 AM,5:54 PM,9:16,8:43 AM,6:27 PM,9:43,167h 33m
4,2,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,Absent,-,-,Absent,-,-,...,Absent,-,-,Absent,-,-,Absent,-,-,0h 0m

In [4]:
df.head()

,ATTENDANCE SHEET PPMC,Unnamed: 1,Unnamed: 2,Unnamed: 3,Attendance Period: 2026-01-01 to 2026-01-30,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sr,Employee ID,Employee Name,Department,2026-01-01,NaN,NaN,2026-01-02,NaN,NaN,...,2026-01-28,NaN,NaN,2026-01-29,NaN,NaN,2026-01-30,NaN,NaN,TOTAL HRS
2,NaN,NaN,NaN,NaN,IN,OUT,HRS,IN,OUT,HRS,...,IN,OUT,HRS,IN,OUT,HRS,IN,OUT,HRS,NaN
3,1,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,Absent,-,-,8:30 AM,4:33 PM,8:03,...,8:44 AM,5:51 PM,9:07,8:38 AM,5:54 PM,9:16,8:43 AM,6:27 PM,9:43,167h 33m
4,2,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,Absent,-,-,Absent,-,-,...,Absent,-,-,Absent,-,-,Absent,-,-,0h 0m

In [5]:
df.columns = df.iloc[1]   # set 2nd row as header
df = df[2:].reset_index(drop=True)  # remove first two rows and reset index
df.head()

1,Sr,Employee ID,Employee Name,Department,2026-01-01,NaN,NaN,2026-01-02,NaN,NaN,...,2026-01-28,NaN,NaN,2026-01-29,NaN,NaN,2026-01-30,NaN,NaN,TOTAL HRS
0,NaN,NaN,NaN,NaN,IN,OUT,HRS,IN,OUT,HRS,...,IN,OUT,HRS,IN,OUT,HRS,IN,OUT,HRS,NaN
1,1,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,Absent,-,-,8:30 AM,4:33 PM,8:03,...,8:44 AM,5:51 PM,9:07,8:38 AM,5:54 PM,9:16,8:43 AM,6:27 PM,9:43,167h 33m
2,2,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,Absent,-,-,Absent,-,-,...,Absent,-,-,Absent,-,-,Absent,-,-,0h 0m
3,3,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,8:48 AM,4:53 PM,8:04,8:30 AM,4:12 PM,7:42,...,8:36 AM,5:53 PM,9:16,8:39 AM,5:57 PM,9:17,8:37 AM,6:26 PM,9:48,189h 58m
4,4,985,Mr. Muhammad Ehsan Irshad,Integrated Planning and Economic Analysis,8:16 AM,5:44 PM,9:28,8:12 AM,-,-,...,8:31 AM,5:17 PM,8:46,8:27 AM,6:47 PM,10:19,8:23 AM,5:13 PM,8:50,180h 37m

In [13]:
df.to_csv("attendance_2026-01-01_to_2026-01-30.csv", index=False)

In [18]:
import pandas as pd
import json

df = pd.read_csv("attendance_2026-01-01_to_2026-01-30.csv", header=1)

# Clean headers
df.columns = df.columns.str.strip()
df = df.dropna(how="all").reset_index(drop=True)

employee = {
    "employee_id": df.iloc[0][df.columns[1]],
    "employee_name": df.iloc[0][df.columns[2]],
    "department": df.iloc[0][df.columns[3]],
    "attendance": {}
}

cols = list(df.columns)
i = 4

while i < len(cols) - 1:  # prevent index error

    date = cols[i]

    # Skip if this column doesn't look like a date
    if not str(date).startswith("2026"):
        i += 1
        continue

    in_time = df.iloc[0][cols[i]]

    # Check if OUT column exists
    if i + 1 < len(cols):
        out_time = df.iloc[0][cols[i + 1]]
    else:
        out_time = None

    # Handle absent / empty
    if pd.isna(in_time) or str(in_time).lower() == "absent":
        in_time = "0:00"

    if pd.isna(out_time):
        out_time = "0:00"

    employee["attendance"][date] = {
        "in": str(in_time),
        "out": str(out_time)
    }

    i += 3  # move to next date block

print(json.dumps(employee, indent=2))

{
  "employee_id": 985.0,
  "employee_name": "Mr. Muhammad Ehsan Irshad",
  "department": "Integrated Planning and Economic Analysis",
  "attendance": {}
}

In [26]:
import pandas as pd
import json

# ==============================
# 1. Read CSV with 2 header rows
# ==============================
file_path = "attendance_2026-01-01_to_2026-01-30.csv"
df = pd.read_csv(file_path, header=[0, 1])

# ==============================
# 2. Flatten multi-level columns
# ==============================
new_cols = []
for col1, col2 in df.columns:
    col1 = str(col1).strip()
    col2 = str(col2).strip()
    if col2 == "" or "Unnamed" in col2:
        new_cols.append(col1)
    else:
        new_cols.append(f"{col1}_{col2}")

df.columns = new_cols
df = df.dropna(how="all").reset_index(drop=True)

# ==============================
# 3. Build JSON for all employees
# ==============================
all_employees = []

for idx, row in df.iterrows():
    employee = {
        "employee_id": row["Employee ID"],
        "employee_name": row["Employee Name"],
        "department": row["Department"],
        "attendance": {}
    }

    for col in df.columns:
        if col.endswith("_IN"):
            date = col.replace("_IN", "")
            in_time = row[col]

            out_col = f"{date}_OUT"
            hrs_col = f"{date}_HRS"

            # Get OUT and HRS if columns exist
            out_time = row[out_col] if out_col in df.columns else None
            hrs = row[hrs_col] if hrs_col in df.columns else None

            # Handle explicit 'Absent'
            if str(in_time).lower() == "absent":
                in_time = "0:00"
                out_time = "0:00"
                hrs = "0:00"
            else:
                # Replace dash or NaN with None
                if pd.isna(in_time) or in_time == "-":
                    in_time = None
                if pd.isna(out_time) or out_time == "-":
                    out_time = None
                if pd.isna(hrs) or hrs == "-":
                    hrs = None

            employee["attendance"][date] = {
                "in": str(in_time) if in_time else None,
                "out": str(out_time) if out_time else None,
                "hrs": str(hrs) if hrs else None
            }

    all_employees.append(employee)

# ==============================
# 4. Save JSON
# ==============================
with open("attendance.json", "w") as f:
    json.dump(all_employees, f, indent=2)

# Print first employee for verification
print(json.dumps(all_employees[0], indent=2))

{
  "employee_id": 985.0,
  "employee_name": "Mr. Muhammad Ehsan Irshad",
  "department": "Integrated Planning and Economic Analysis",
  "attendance": {
    "2026-01-01": {
      "in": "0:00",
      "out": "0:00",
      "hrs": "0:00"
    },
    "2026-01-02": {
      "in": "8:30 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-05": {
      "in": "8:28 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-06": {
      "in": "8:39 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-07": {
      "in": "8:28 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-08": {
      "in": "8:28 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-09": {
      "in": "8:32 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-12": {
      "in": "8:35 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-13": {
      "in": "8:20 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-14": {
      "in": "8:29 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-15": {
      "in": "8:34 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-16": {
      "in": "8:37 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-19": {
      "in": "5:12 PM",
      "out": null,
      "hrs": null
    },
    "2026-01-20": {
      "in": "8:42 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-21": {
      "in": "8:47 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-22": {
      "in": "8:44 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-23": {
      "in": "4:40 PM",
      "out": null,
      "hrs": null
    },
    "2026-01-26": {
      "in": "8:35 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-27": {
      "in": "8:40 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-28": {
      "in": "8:44 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-29": {
      "in": "8:38 AM",
      "out": null,
      "hrs": null
    },
    "2026-01-30": {
      "in": "8:43 AM",
      "out": null,
      "hrs": null
    }
  }
}

In [28]:
import csv
import json

def transform_attendance(file_path):
    with open(file_path, mode='r', encoding='utf-8') as f:
        reader = list(csv.reader(f))
        
        # Row 0: Dates (e.g., Sr, Employee ID, ..., 2026-01-01, , , 2026-01-02)
        # Row 1: Labels (e.g., , , , , IN, OUT, HRS, IN, OUT, HRS)
        header_dates = reader[0]
        data_rows = reader[2:] # Actual data starts from index 2
        
        employees_json = []

        for row in data_rows:
            # Skip empty rows or footer rows (like the PPMC Synergy download note)
            if not row or len(row) < 4 or not row[1].isdigit():
                continue
                
            emp_data = {
                "employee_id": float(row[1]),
                "employee_name": row[2],
                "department": row[3],
                "attendance": {}
            }
            
            # Attendance data starts at index 4
            # We jump 3 columns at a time (IN, OUT, HRS)
            col_idx = 4
            for i in range(4, len(header_dates) - 1, 3):
                date_label = header_dates[i].strip()
                if not date_label:
                    continue
                
                # Get the triplet
                val_in = row[col_idx] if col_idx < len(row) else "-"
                val_out = row[col_idx + 1] if col_idx + 1 < len(row) else "-"
                val_hrs = row[col_idx + 2] if col_idx + 2 < len(row) else "-"
                
                # Clean "Absent" or "-" values to match your requested format
                if val_in == "Absent":
                    entry = {"in": "0:00", "out": "0:00", "hrs": "0:00"}
                else:
                    entry = {
                        "in": val_in if val_in != "-" else None,
                        "out": val_out if val_out != "-" else None,
                        "hrs": val_hrs if val_hrs != "-" else None
                    }
                
                emp_data["attendance"][date_label] = entry
                col_idx += 3
            
            employees_json.append(emp_data)
            
        return employees_json

# Execution
try:
    result = transform_attendance('attendance_2026-01-01_to_2026-01-30.csv')
    # Print the first employee record as a sample
    print(json.dumps(result[0], indent=2))
except FileNotFoundError:
    print("Error: file.csv not found.")

{
  "employee_id": 985.0,
  "employee_name": "Mr. Muhammad Ehsan Irshad",
  "department": "Integrated Planning and Economic Analysis",
  "attendance": {
    "2026-01-01": {
      "in": "0:00",
      "out": "0:00",
      "hrs": "0:00"
    },
    "2026-01-02": {
      "in": "8:30 AM",
      "out": "4:33 PM",
      "hrs": "8:03"
    },
    "2026-01-05": {
      "in": "8:28 AM",
      "out": "5:27 PM",
      "hrs": "8:59"
    },
    "2026-01-06": {
      "in": "8:39 AM",
      "out": "5:34 PM",
      "hrs": "8:55"
    },
    "2026-01-07": {
      "in": "8:28 AM",
      "out": "5:37 PM",
      "hrs": "9:08"
    },
    "2026-01-08": {
      "in": "8:28 AM",
      "out": "6:22 PM",
      "hrs": "9:53"
    },
    "2026-01-09": {
      "in": "8:32 AM",
      "out": "2:16 PM",
      "hrs": "5:43"
    },
    "2026-01-12": {
      "in": "8:35 AM",
      "out": "5:39 PM",
      "hrs": "9:04"
    },
    "2026-01-13": {
      "in": "8:20 AM",
      "out": "4:37 PM",
      "hrs": "8:17"
    },
    "2026-01-14": {
      "in": "8:29 AM",
      "out": "4:42 PM",
      "hrs": "8:12"
    },
    "2026-01-15": {
      "in": "8:34 AM",
      "out": "4:51 PM",
      "hrs": "8:16"
    },
    "2026-01-16": {
      "in": "8:37 AM",
      "out": "6:27 PM",
      "hrs": "9:50"
    },
    "2026-01-19": {
      "in": "5:12 PM",
      "out": null,
      "hrs": null
    },
    "2026-01-20": {
      "in": "8:42 AM",
      "out": "5:56 PM",
      "hrs": "9:13"
    },
    "2026-01-21": {
      "in": "8:47 AM",
      "out": "6:16 PM",
      "hrs": "9:29"
    },
    "2026-01-22": {
      "in": "8:44 AM",
      "out": "6:21 PM",
      "hrs": "9:37"
    },
    "2026-01-23": {
      "in": "4:40 PM",
      "out": "4:40 PM",
      "hrs": "0:00"
    },
    "2026-01-26": {
      "in": "8:35 AM",
      "out": "4:03 PM",
      "hrs": "7:27"
    },
    "2026-01-27": {
      "in": "8:40 AM",
      "out": "6:02 PM",
      "hrs": "9:21"
    },
    "2026-01-28": {
      "in": "8:44 AM",
      "out": "5:51 PM",
      "hrs": "9:07"
    },
    "2026-01-29": {
      "in": "8:38 AM",
      "out": "5:54 PM",
      "hrs": "9:16"
    },
    "2026-01-30": {
      "in": "8:43 AM",
      "out": "6:27 PM",
      "hrs": "9:43"
    }
  }
}